######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 3 13:36:57 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . includes src
INCLUDEPATH += . includes

# Input
HEADERS += includes/Layout.h includes/MyAweSomeBox.h
SOURCES += src/Layout.cpp src/main.cpp src/MyAweSomeBox.cpp
