######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 28 12:28:53 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MyAweSomeBox.h
SOURCES += main.cpp MyAweSomeBox.cpp
