######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 10 13:54:36 2010
######################################################################

QT += network

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CegTcpServer.h \
    ProtocolServerVNC.h
SOURCES += CegTcpServer.cpp main.cpp \
    ProtocolServerVNC.cpp
